DartApp/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DartApp.Models.Entities;
using DartApp.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace DartApp.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly DartAppDatabaseContext _context;

        public GamesController(DartAppDatabaseContext context)
        {
            _context = context;
        }

        public void CheckWinner(int id)
        {
            var game = _context.Games.Include(g => g.Sets).ToList().Find(g => g.GameId == id);
            _context.Update(game);
            var sets = game.Sets;

            int winsPlayerOne = 0;
            int winsPlayerTwo = 0;

            foreach (Set set in sets)
            {
                var winnerId = set.WinnerId;

                if (winnerId == game.PlayerOneId)
                {
                    winsPlayerOne++;
                }
                else if (winnerId == game.PlayerTwoId)
                {
                    winsPlayerTwo++;
                }
                else
                {
                    continue;
                }

                int setWinsForGameWin = game.SetAmount / 2 + 1;
                if (setWinsForGameWin == winsPlayerOne)
                {
                    game.WinnerId = game.PlayerOneId;
                }
                else if (setWinsForGameWin == winsPlayerTwo)
                {
                    game.WinnerId = game.PlayerTwoId;
                }
                else
                {
                    game.WinnerId = null;
                }
            }
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var dartAppDatabaseContext = _context.Games
                .Include(g => g.PlayerOne)
                .Include(g => g.PlayerTwo)
                .Include(g => g.Winner)
                .OrderByDescending(g => g.GameDate);
            return View(await dartAppDatabaseContext.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var game = await _context.Games
                .Include(g => g.PlayerOne)
                .Include(g => g.PlayerTwo)
                .Include(g => g.Winner)
                .Include(g => g.Sets)
                .ThenInclude(s => s.Legs)
                .ThenInclude(l => l.Throws)
                .FirstOrDefaultAsync(m => m.GameId == id);
            if (game == null)
                return NotFound();

            ViewData["Summary"] = await GetGameSummary(game.GameId);
            ViewData["Stats"] = GetStats(game);
            return View(game);

        }

        //POST: Games/Import
        public IActionResult Import()
        {
            return View();
        }

        //import
        [HttpPost]
        public async Task<IActionResult> Import(IFormFile file)
        {
            if (file != null)
            {
                if (file.Length < 4096 && file.FileName.EndsWith(".JSON"))
                {
                    ViewBag.Message = "Bestand geupload! Even geduld...";
                    Debug.WriteLine(file.FileName);

                    var result = new StringBuilder();
                    using (var reader = new StreamReader(file.OpenReadStream()))
                    {
                        while (reader.Peek() >= 0)
                            result.AppendLine(await reader.ReadLineAsync());
                    }

                    try
                    {
                        var newGameId = await Importer(result.ToString());
                        return RedirectToAction("Details", new { Id = newGameId });
                    }
                    catch
                    {
                        ViewBag.Message = "Er ging iets fout bij het importeren";
                    }
                }
                else if (!file.FileName.EndsWith(".json"))
                {
                    ViewBag.Message = "Foutief bestand geupload. Upload een .json bestand.";
                }
                else if (file.Length > 4096)
                {
                    ViewBag.Message = "Bestand te groot. Upload een kleiner bestand.";
                }
            }
            else
            {
                ViewBag.Message = "Geen bestand geupload, selecteer een bestand.";
            }

            return View();
        }

        private async Task<int> Importer(string stringData)
        {
            var game = Game.FromJson(stringData);
            var playerOneId = await GetPlayerIdOrCreateNew(game.PlayerOneName);
            var playerTwoId = await GetPlayerIdOrCreateNew(game.PlayerTwoName);
            var playerNameMap = new Dictionary<string, int>()
            {
                { game.PlayerOneName, playerOneId },
                { game.PlayerTwoName, playerTwoId }
            };

            var newGame = new Game()
            {
                GameDate = game.GameDate,
                StartingPoints = game.StartingPoints,
                LegAmount = game.LegAmount,
                SetAmount = game.SetAmount,
                PlayerOneId = playerOneId,
                PlayerTwoId = playerTwoId,
                Sets = new List<Set>()
            };
            if (game.WinnerName != null)
                newGame.WinnerId = playerNameMap[game.WinnerName];

            foreach (var set in game.Sets)
            {
                var newSet = new Set()
                {
                    Legs = new List<Leg>(),
                    SequenceNumber = set.SequenceNumber
                };
                if (set.WinnerName != null)
                    newSet.WinnerId = playerNameMap[set.WinnerName];
                
                foreach (var leg in set.Legs)
                {
                    var newLeg = new Leg()
                    {
                        SequenceNumber = leg.SequenceNumber,
                        Throws = new List<Throw>()
                    };
                    if (leg.WinnerName != null)
                        newLeg.WinnerId = playerNameMap[leg.WinnerName];

                    foreach (var @throw in leg.Throws)
                    {
                        var newThrow = new Throw()
                        {
                            PlayerId = playerNameMap[@throw.PlayerName],
                            FirstScore = @throw.FirstScore,
                            FirstScoreMultiplier = @throw.FirstScoreMultiplier,
                            SecondScore = @throw.SecondScore,
                            SecondScoreMultiplier = @throw.SecondScoreMultiplier,
                            ThirdScore = @throw.ThirdScore,
                            ThirdScoreMultiplier = @throw.ThirdScoreMultiplier,
                            SequenceNumber = @throw.SequenceNumber
                        };

                        newLeg.Throws.Add(newThrow);
                    }

                    newSet.Legs.Add(newLeg);
                }

                newGame.Sets.Add(newSet);
            }

            _context.Add(newGame);
            await _context.SaveChangesAsync();
            return newGame.GameId;
        }


        public async Task<int> GetPlayerIdOrCreateNew(string playerName)
        {
            var player = await _context.Players
                .Where(p => p.Name == playerName)
                .FirstOrDefaultAsync();
            if (player != null)
                return player.PlayerId;

            var newPlayer = new Player() { Name = playerName };
            _context.Add(newPlayer);
            await _context.SaveChangesAsync();
            return newPlayer.PlayerId;
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name");
            ViewData["PlayerTwoId"] = new SelectList(_context.Players, "PlayerId", "Name");
            ViewData["WinnerId"] = new SelectList(_context.Players, "PlayerId", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("GameId,GameDate,PlayerOneId,PlayerTwoId,WinnerId,LegAmount,SetAmount,StartingPoints")]
            Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerOneId);
            ViewData["PlayerTwoId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerTwoId);
            ViewData["WinnerId"] = new SelectList(_context.Players, "PlayerId", "Name", game.WinnerId);
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerOneId);

DartApp/Controllers/PlayersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DartApp.Models.Entities;
using Microsoft.AspNetCore.Authorization;

namespace DartApp.Controllers
{
    [Authorize]
    public class PlayersController : Controller
    {
        private readonly DartAppDatabaseContext _context;

        public PlayersController(DartAppDatabaseContext context)
        {
            _context = context;
        }

        // GET: Players
        public async Task<IActionResult> Index()
        {
            return View(await _context.Players.ToListAsync());
        }

        // GET: Players/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.PlayerId == id);
            if (player == null)
            {
                return NotFound();
            }

            ViewData["Games"] = _context.Games.Where(g => g.PlayerOneId == id || g.PlayerTwoId == id)
                                    .Include(g => g.PlayerOne)
                                    .Include(g => g.PlayerTwo)
                                    .Include(g => g.Winner);

            return View(player);
        }

        // GET: Players/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId,Name")] Player player)
        {
            if (ModelState.IsValid)
            {
                _context.Add(player);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerId,Name")] Player player)
        {
            if (id != player.PlayerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.PlayerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Players/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _context.Players
                .FirstOrDefaultAsync(m => m.PlayerId == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var player = await _context.Players.FindAsync(id);
            _context.Players.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
            return _context.Players.Any(e => e.PlayerId == id);
        }
    }
}

DartApp/Views/Shared/_Games.cshtml
@model IEnumerable<DartApp.Models.Entities.Game>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GameDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LegAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SetAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartingPoints)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerOne)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerTwo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Winner)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GameDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LegAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SetAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartingPoints)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerOne.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerTwo.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Winner.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-controller="Games" asp-route-id="@item.GameId">Edit</a> |
                    <a asp-action="Details" asp-controller="Games" asp-route-id="@item.GameId">Details</a> |
                    <a asp-action="Delete" asp-controller="Games" asp-route-id="@item.GameId">Delete</a> |
                    <a asp-action="Export" asp-controller="Games" asp-route-id="@item.GameId">Export</a>
                </td>
            </tr>
        }
    </tbody>
</table>

DartApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dart App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dart App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Wedstrijden</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Spelers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Beheer groep 1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>