DartApp/Models/Entities/Leg.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace DartApp.Models.Entities
{
    public class Leg
    {
        [JsonIgnore]
        public int LegId { get; set; }
        public int SequenceNumber { get; set; }

        [JsonIgnore]
        public int SetId { get; set; }
        [JsonIgnore]
        public Set Set { get; set; }

        [JsonIgnore]
        public int? WinnerId { get; set; }
        [JsonIgnore]
        public Player Winner { get; set; }

        private string _winnerName;
        [NotMapped]
        public string WinnerName
        {
            get => _winnerName ?? Winner?.Name;
            set => _winnerName = value;
        }

        public ICollection<Throw> Throws { get; set; }
    }
}

DartApp/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DartApp.Models.Entities;
using DartApp.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace DartApp.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly DartAppDatabaseContext _context;

        public GamesController(DartAppDatabaseContext context)
        {
            _context = context;
        }

        public void CheckWinner(int id)
        {
            var game = _context.Games.Include(g => g.Sets).ToList().Find(g => g.GameId == id);
            _context.Update(game);
            var sets = game.Sets;

            int winsPlayerOne = 0;
            int winsPlayerTwo = 0;

            foreach (Set set in sets)
            {
                var winnerId = set.WinnerId;

                if (winnerId == game.PlayerOneId)
                {
                    winsPlayerOne++;
                }
                else if (winnerId == game.PlayerTwoId)
                {
                    winsPlayerTwo++;
                }
                else
                {
                    continue;
                }

                int setWinsForGameWin = game.SetAmount / 2 + 1;
                if (setWinsForGameWin == winsPlayerOne)
                {
                    game.WinnerId = game.PlayerOneId;
                }
                else if (setWinsForGameWin == winsPlayerTwo)
                {
                    game.WinnerId = game.PlayerTwoId;
                }
                else
                {
                    game.WinnerId = null;
                }
            }
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var dartAppDatabaseContext = _context.Games
                .Include(g => g.PlayerOne)
                .Include(g => g.PlayerTwo)
                .Include(g => g.Winner)
                .OrderByDescending(g => g.GameDate);
            return View(await dartAppDatabaseContext.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var game = await _context.Games
                .Include(g => g.PlayerOne)
                .Include(g => g.PlayerTwo)
                .Include(g => g.Winner)
                .Include(g => g.Sets)
                .ThenInclude(s => s.Legs)
                .ThenInclude(l => l.Throws)
                .FirstOrDefaultAsync(m => m.GameId == id);
            if (game == null)
                return NotFound();

            ViewData["Summary"] = await GetGameSummary(game.GameId);
            ViewData["Stats"] = GetStats(game);
            return View(game);

        }

        //POST: Games/Import
        public IActionResult Import()
        {
            return View();
        }

        //import
        [HttpPost]
        public async Task<IActionResult> Import(IFormFile file)
        {
            if (file != null)
            {
                if (file.Length < 4096 && file.FileName.EndsWith(".JSON"))
                {
                    ViewBag.Message = "Bestand geupload! Even geduld...";
                    Debug.WriteLine(file.FileName);

                    var result = new StringBuilder();
                    using (var reader = new StreamReader(file.OpenReadStream()))
                    {
                        while (reader.Peek() >= 0)
                            result.AppendLine(await reader.ReadLineAsync());
                    }

                    try
                    {
                        var newGameId = await Importer(result.ToString());
                        return RedirectToAction("Details", new { Id = newGameId });
                    }
                    catch
                    {
                        ViewBag.Message = "Er ging iets fout bij het importeren";
                    }
                }
                else if (!file.FileName.EndsWith(".json"))
                {
                    ViewBag.Message = "Foutief bestand geupload. Upload een .json bestand.";
                }
                else if (file.Length > 4096)
                {
                    ViewBag.Message = "Bestand te groot. Upload een kleiner bestand.";
                }
            }
            else
            {
                ViewBag.Message = "Geen bestand geupload, selecteer een bestand.";
            }

            return View();
        }

        private async Task<int> Importer(string stringData)
        {
            var game = Game.FromJson(stringData);
            var playerOneId = await GetPlayerIdOrCreateNew(game.PlayerOneName);
            var playerTwoId = await GetPlayerIdOrCreateNew(game.PlayerTwoName);
            var playerNameMap = new Dictionary<string, int>()
            {
                { game.PlayerOneName, playerOneId },
                { game.PlayerTwoName, playerTwoId }
            };

            var newGame = new Game()
            {
                GameDate = game.GameDate,
                StartingPoints = game.StartingPoints,
                LegAmount = game.LegAmount,
                SetAmount = game.SetAmount,
                PlayerOneId = playerOneId,
                PlayerTwoId = playerTwoId,
                Sets = new List<Set>()
            };
            if (game.WinnerName != null)
                newGame.WinnerId = playerNameMap[game.WinnerName];

            foreach (var set in game.Sets)
            {
                var newSet = new Set()
                {
                    Legs = new List<Leg>(),
                    SequenceNumber = set.SequenceNumber
                };
                if (set.WinnerName != null)
                    newSet.WinnerId = playerNameMap[set.WinnerName];
                
                foreach (var leg in set.Legs)
                {
                    var newLeg = new Leg()
                    {
                        SequenceNumber = leg.SequenceNumber,
                        Throws = new List<Throw>()
                    };
                    if (leg.WinnerName != null)
                        newLeg.WinnerId = playerNameMap[leg.WinnerName];

                    foreach (var @throw in leg.Throws)
                    {
                        var newThrow = new Throw()
                        {
                            PlayerId = playerNameMap[@throw.PlayerName],
                            FirstScore = @throw.FirstScore,
                            FirstScoreMultiplier = @throw.FirstScoreMultiplier,
                            SecondScore = @throw.SecondScore,
                            SecondScoreMultiplier = @throw.SecondScoreMultiplier,
                            ThirdScore = @throw.ThirdScore,
                            ThirdScoreMultiplier = @throw.ThirdScoreMultiplier,
                            SequenceNumber = @throw.SequenceNumber
                        };

                        newLeg.Throws.Add(newThrow);
                    }

                    newSet.Legs.Add(newLeg);
                }

                newGame.Sets.Add(newSet);
            }

            _context.Add(newGame);
            await _context.SaveChangesAsync();
            return newGame.GameId;
        }


        public async Task<int> GetPlayerIdOrCreateNew(string playerName)
        {
            var player = await _context.Players
                .Where(p => p.Name == playerName)
                .FirstOrDefaultAsync();
            if (player != null)
                return player.PlayerId;

            var newPlayer = new Player() { Name = playerName };
            _context.Add(newPlayer);
            await _context.SaveChangesAsync();
            return newPlayer.PlayerId;
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name");
            ViewData["PlayerTwoId"] = new SelectList(_context.Players, "PlayerId", "Name");
            ViewData["WinnerId"] = new SelectList(_context.Players, "PlayerId", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("GameId,GameDate,PlayerOneId,PlayerTwoId,WinnerId,LegAmount,SetAmount,StartingPoints")]
            Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerOneId);
            ViewData["PlayerTwoId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerTwoId);
            ViewData["WinnerId"] = new SelectList(_context.Players, "PlayerId", "Name", game.WinnerId);
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games.FindAsync(id);
            if (game == null)
            {
                return NotFound();
            }

            ViewData["PlayerOneId"] = new SelectList(_context.Players, "PlayerId", "Name", game.PlayerOneId);

DartApp/Views/Legs/Create.cshtml
@model DartApp.Models.Entities.Leg

@{
    ViewData["Title"] = "Create";

    var sequenceNumber = Model?.SequenceNumber ?? ViewData["SequenceNumber"];
}

<h1>Create</h1>

<h4>Leg</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SetId" value="@ViewData["SetId"]"/>
            <input type="hidden" asp-for="SequenceNumber" value="@sequenceNumber"/>
            <div class="form-group">
                <label asp-for="SequenceNumber" class="control-label"></label>
                <input asp-for="SequenceNumber" class="form-control" value="@sequenceNumber" disabled />
                <span asp-validation-for="SequenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Games" asp-route-id="@ViewData["GameId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DartApp/Views/Legs/Delete.cshtml
@model DartApp.Models.Entities.Leg

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leg</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SequenceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SequenceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Set.SetId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Winner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Winner.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="LegId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Games" asp-route-id="@Model.Set.GameId">Back to List</a>
    </form>
</div>

DartApp/Views/Legs/Details.cshtml
@model DartApp.Models.Entities.Leg

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Leg</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SequenceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SequenceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Set)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Set.SetId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Winner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Winner.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.LegId">Edit</a> |
    <a asp-action="Details" asp-controller="Games" asp-route-id="@Model.Set.GameId">Back to List</a>
</div>

DartApp/Views/Legs/Edit.cshtml
@model DartApp.Models.Entities.Leg

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Leg</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="LegId" />
            <input type="hidden" asp-for="SetId" />
            <div class="form-group">
                <label asp-for="SequenceNumber" class="control-label"></label>
                <input asp-for="SequenceNumber" class="form-control" />
                <span asp-validation-for="SequenceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="Games" asp-route-id="@Model.Set.GameId" >Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DartApp/Views/Legs/Index.cshtml
@model IEnumerable<DartApp.Models.Entities.Leg>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SequenceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Set)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Winner)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SequenceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Set.SetId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Winner.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.LegId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.LegId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.LegId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>